#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Maker @ IT Nerd Space

# Short bio or description (displayed in the header)
description: My blog about Hacking and Making

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/ITNerdSpace/maker/raw/master/images/logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: adumont
  instagram:
  linkedin: alexandredumont
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: adumont
  stackoverflow: users/728281/alexandre-dumont # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: http-itnerd-space

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:  UA-75609256-3

# Google Adsense Id, e.g. ca-pub-0000000000000000
adsbygoogle: ca-pub-2190762825637663

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://maker.itnerd.space

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

remote_theme: brianmaierjr/long-haul

collections:
  tag:
    output: true

# Prose.io block, reference: https://github.com/prose/prose/wiki/Prose-Configuration
# inspired from https://raw.githubusercontent.com/hmfaysal/Notepad/gh-pages/_config.yml

prose:
  rooturl: '_posts'
  siteurl: 'http://maker.itnerd.space/'
  users:
    - login: "adumont"
      user: "Alexandre Dumont"  
  relativeLinks: 'https://github.com/ITNerdSpace/maker/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "author"
        field:
          label: "Author"
          element: "text"
          value: CURRENT_USER
      - name: "last_modified_at"
        field:
          element: "text"
          label: "When has this page been last modified?"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add tags"
          placeholder: "Choose tags that apply"
          value: Automaton
          options:
            - name: "Cellular Automaton"
              value: Automaton
            - name: "HRM CPU"
              value: hrmcpu
          alterable: true
      # - name: "tags"
      #   field:
      #     element: "text"
      #     label: "Tags"
      #     placeholder: "Enter tags, separated by spaces"          
      - name: "image"
        field:
          element: "text"
          label: "Featured Image URL"
          placeholder: "somefile.jpg"

# include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
